site_name: vengi - voxel tools
site_author: Martin Gerhardy
site_description: Voxel editor for linux windows and macosx
docs_dir: docs
site_dir: build/docs
repo_url: https://github.com/vengi-voxel/vengi
repo_name: GitHub

theme:
  custom_dir: docs/theme
  name: material
  highlightjs: true
  hljs_languages: [cpp]

markdown_extensions:
  - toc:
      toc_depth: 2

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MartinGerhardy

nav:
  - README.md
  - CHANGELOG.md
  - Basics:
      - Dependencies.md
      - Compilation.md
      - Configuration.md
      - Formats.md
      - LUAScript.md
      - Palette.md
  - VoxConvert:
      - voxconvert/Index.md
      - voxconvert/Usage.md
      - voxconvert/Configuration.md
      - voxconvert/Examples.md
      - voxconvert/Screenshots.md
  - VoxEdit:
      - voxedit/Index.md
      - voxedit/Features.md
      - voxedit/Usage.md
      - voxedit/Controls.md
      - voxedit/Configuration.md
      - voxedit/Screenshots.md
  - Thumbnailer:
      - thumbnailer/Index.md
      - thumbnailer/Examples.md
  - Development:
      - Basic: Basics.md
      - Visual Tests: VisualTests.md
      - Shader integration: ShaderTool.md
      - Compute Shader integration: ComputeShaderTool.md
