site_name: vengi - voxel engine and its tools
site_author: Martin Gerhardy
site_description: Voxel editor for linux windows and macosx
docs_dir: docs
site_dir: build/docs
repo_url: https://github.com/mgerhardy/engine
repo_name: GitHub

theme:
  custom_dir: docs/theme
  name: readthedocs
  highlightjs: true
  hljs_languages: [cpp]

markdown_extensions:
  - toc:
      toc_depth: 2

nav:
  - README.md
  - CHANGELOG.md
  - Basics:
      - Dependencies.md
      - Compilation.md
      - Configuration.md
      - Formats.md
      - LUAScript.md
      - Palette.md
  - VoxConvert:
      - voxconvert/Index.md
      - voxconvert/Usage.md
      - voxconvert/Examples.md
      - voxconvert/Screenshots.md
  - VoxEdit:
      - voxedit/Index.md
      - voxedit/Features.md
      - voxedit/Configuration.md
      - voxedit/Screenshots.md
  - Thumbnailer:
      - thumbnailer/Index.md
      - thumbnailer/Examples.md
  - Development:
      - Visual Tests: VisualTests.md
      - Shader integration: ShaderTool.md
      - Compute Shader integration: ComputeShaderTool.md
      - Persistence: Persistence.md
      - Animations: Animations.md
      - Attributes: Attributes.md
      - Network: Network.md
      - AI development: AIRemoteDebugger.md
      - OpenWorld: openworld/Index.md
      - MapView: mapview/Index.md
